### Get localhost:3000 
GET http://localhost:3000/

### Register
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "username": "finkaamel",
    "email": "finkaamel@banksampah.com",
    "password": "P@ssw0rd"
}

### LOGIN
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "username": "superadmin",
    "password": "P@ssw0rd"
}

### FORGOT PASSWORD
POST http://localhost:3000/forgotpassword HTTP/1.1
Content-Type: application/json

{
  "email": "email"
}

### FORGOT USERNAME
POST  http://localhost:3000/forgotusername HTTP/1.1
Content-Type: application/json

{
  "email": "email"
}

### UPDATE PASSWORD BY LINK
POST http://localhost:3000/updatepasswordbylink HTTP/1.1
Content-Type: application/json

{
  "iduser": "",
  "newpassword": ""
}

### GET ALL USER
GET http://localhost:3000/users/all HTTP/1.1
Content-Type: application/json

### GET ALL PRIVILEDGE
GET http://localhost:3000/privilege/all HTTP/1.1
Content-Type: application/json

