# GET http://localhost:3000/

### Register 
POST http://localhost:3000/users/save HTTP/1.1
Content-Type: application/json

{
    "username": "superadmin",
    "email": "superadmin@banksampah.com",
    "password": "P@ssw0rd",
    "lastlogin":null,
    "status":"A",
    "issuperadmin":true
}

### LOGIN
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "username": "aanmaryanto",
    "password": "P@ssw0rd"
}

### ALL USER
GET http://localhost:3000/banksampah_api/user
Content-Type: application/json
