### Get localhost:3000 
GET http://localhost:3000/

### Register
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "username": "finkaamel",
    "email": "admin_finkaamel@banksampah.com",
    "password": "P@ssw0rd"
}

### LOGIN
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "username": "superadmin",
    "password": "P@ssw0rd"
}