version: "3"
services:
  db:
    image: mysql:8.0.32-debian
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DOCKER_DATABASE_PASSWORD
      - MYSQL_USER=$DOCKER_DATABASE_USER
      - MYSQL_PASSWORD=$DOCKER_DATABASE_PASSWORD
      - MYSQL_DATABASE=$DOCKER_DATABASE_DB
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - db
    image: nodejs_16.15.1_alpine
    env_file:
      - ./.env
    environment:
      - HOST=db
      - USERNAME=$USERNAME
      - PASSWORD=$PASSWORD
      - DATABASE=$DATABASE
      - SALT=$SALT
      - GMAIL_SERVICE_NAME=$GMAIL_SERVICE_NAME
      - GMAIL_SERVICE_HOST=$GMAIL_SERVICE_HOST
      - GMAIL_SERVICE_SECURE=$GMAIL_SERVICE_SECURE
      - GMAIL_SERVICE_TLS=$GMAIL_SERVICE_TLS
      - GMAIL_SERVICE_PORT=$GMAIL_SERVICE_PORT
    stdin_open: true
    tty: true
    ports:
      - "8000:3000"
volumes:
  db: