version: "3.1"
services:
  db:
    image: mysql:8.0.32-debian
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DOCKER_DATABASE_PASSWORD
      - MYSQL_USER=$DOCKER_DATABASE_USER
      - MYSQL_PASSWORD=$DOCKER_DATABASE_PASSWORD
      - MYSQL_DATABASE=$DOCKER_DATABASE_DB
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - db
    build: /home/aan/work-dir
    env_file:
      - ./.env
    ports:
      - "8000:3000"
    environment:
      - HOST=db
      - USERNAME=$USERNAME
      - PASSWORD=$PASSWORD
      - DATABASE=$DATABASE
      - SALT=$SALT
      - GMAIL_SERVICE_NAME=$GMAIL_SERVICE_NAME
      - GMAIL_SERVICE_HOST=$GMAIL_SERVICE_HOST
      - GMAIL_SERVICE_SECURE=$GMAIL_SERVICE_SECURE
      - GMAIL_SERVICE_TLS=$GMAIL_SERVICE_TLS
      - GMAIL_SERVICE_PORT=$GMAIL_SERVICE_PORT
    command: >
      bash -c "npx sequelize-cli db:migrate"
    stdin_open: true
    tty: true
volumes:
  db: